import JSZip from "jszip";
import type { StencilLayers } from "./layerBuilder";

export type ExportOptions = {
  name?: string;
};

/* -------------------------------------------------------
   MAIN EXPORT ENTRY
------------------------------------------------------- */
export async function exportStencilPackage(
  layers: StencilLayers,
  options: ExportOptions = {},
): Promise<Blob> {
  const zip = new JSZip();

  const name = options.name ?? "stencil";

  // -------------------------
  // Add SVG files
  // -------------------------
  zip.file(`${name}-base.svg`, formatSvg(layers.base));
  zip.file(`${name}-cut.svg`, formatSvg(layers.cut));
  zip.file(`${name}-detail.svg`, formatSvg(layers.detail));
  zip.file(`${name}-align.svg`, formatSvg(layers.align));

  // -------------------------
  // Add README for Cricut users
  // -------------------------
  zip.file(
    "README.txt",
    `
STENCIL PACKAGE

Files:
- base.svg   → preview layer
- cut.svg    → Cricut cut layer
- detail.svg → fine detail preview
- align.svg  → registration marks

Recommended workflow:
1. Upload cut.svg to Cricut Design Space
2. Use align.svg for multi-layer alignment
3. Adjust scale only if needed

Generated by Stencil Engine
`.trim(),
  );

  return await zip.generateAsync({ type: "blob" });
}

/* -------------------------------------------------------
   SVG SAFETY NORMALIZER
------------------------------------------------------- */
function formatSvg(svg: string): string {
  let out = svg;

  // ensure XML header
  if (!out.startsWith("<?xml")) {
    out = `<?xml version="1.0" encoding="UTF-8"?>\n` + out;
  }

  // force clean namespace on root
  out = out.replace(
    /<svg\b[^>]*>/i,
    (tag) =>
      `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">`,
  );

  return out;
}