import JSZip from "jszip";

import { layersToSvgSet } from "./svgExporter";
import type { StencilLayerSet } from "../layers/layerBuilder";
import { CORE_NAME, CORE_VERSION } from "../version";

export interface ExportOptions {
  name?: string;
}

export async function exportStencilPackage(
  layers: StencilLayerSet,
  options: ExportOptions = {},
): Promise<Blob> {
  const name = options.name ?? "stencil";
  const svgSet = layersToSvgSet(layers);
  const zip = new JSZip();

  zip.file(`${name}-base.svg`, svgSet.base);
  zip.file(`${name}-cut.svg`, svgSet.cut);
  zip.file(`${name}-detail.svg`, svgSet.detail);
  zip.file(`${name}-align.svg`, svgSet.align);
  zip.file("README.txt", buildReadme(name));

  return zip.generateAsync({ type: "blob" });
}

function buildReadme(name: string): string {
  return `
STENCIL PACKAGE

Files:
- ${name}-base.svg   → preview layer
- ${name}-cut.svg    → Cricut cut layer
- ${name}-detail.svg → fine detail preview
- ${name}-align.svg  → registration marks

Recommended workflow:
1. Upload ${name}-cut.svg to Cricut Design Space
2. Use ${name}-align.svg for multi-layer alignment
3. Adjust scale only if needed

Generated by ${CORE_NAME} ${CORE_VERSION}
`.trim();
}
